# print("hello world!")
# print(2333)
# print(2.333)
# print(True)
# print(False)
# print(())
# print([])
# # print({})
# a=input("请输入第一段内容：")
# b=input("请输入第二段内容：")
# print("两段内容为：",a,b,"两段字数和为：",len(a)+len(b))
